apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-eks
  labels:
    app: express-eks
  namespace: default
spec:
  replicas: 2
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: express-eks
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: express-eks
    spec:
      containers:
        - image: gytisl/express-eks
          imagePullPolicy: Always
          name: express-eks
          ports:
            - containerPort: 3333
