apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-eks
  labels:
    app: express-eks
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: express-eks
  template:
    metadata:
      labels:
        app: express-eks
    spec:
      containers:
        - name: express-eks
          image: gytisl/express-eks
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 3333
